[package]
name = "arc-script-api-python"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT"

[lib]
name = "arc_script_python"
crate-type = ["cdylib"]

[dependencies]
rustpython-vm = { git = "https://github.com/RustPython/RustPython.git" }
# pyo3 = { version = "0.13.1", features = ["extension-module"] }

# [dependencies.arc-script]
# version = "0.0.0"
# path = "../arc-script-core/"
