[package]
name = "hir-lambda-lift"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im-rc.workspace = true
hir.workspace = true
utils.workspace = true
codegen.workspace = true
info.workspace = true
diagnostics.workspace = true
name-gen.workspace = true
stack.workspace = true
