#!/bin/bash

# Try to guess the location of the arc-mlir repository

if [[ -z "$ARC_MLIR" ]] ; then
    ARC_MLIR=$(realpath $(dirname "$(which "$0")")/arc-mlir)
    echo The arc-mlir repository is assumed to be at ${ARC_MLIR}, override by setting ARC_MLIR.
else
    echo ARC_MLIR is ${ARC_MLIR}
fi

if [[ -z "$ARC_MLIR_BUILD" ]] ; then
    echo "No build directory specified with ARC_MLIR_BUILD, assuming ${ARC_MLIR}/build"
    ARC_MLIR_BUILD="${ARC_MLIR}/build"
else
    echo "Will use $ARC_MLIR_BUILD as the scratch directory"
fi

if [ ! -f ${ARC_MLIR}/.guessed-arc-mlir ]; then
    echo "Waiting 10s before proceeding, next run will proceed directly"
    touch ${ARC_MLIR}/.guessed-arc-mlir
    sleep 10
fi

# prefer gold if it is available
ARC_MLIR_LINKER_SELECTION=""
if command -v ld.gold >/dev/null 2>&1; then
    echo "Will use gold"
    ARC_MLIR_LINKER_SELECTION="-DLLVM_USE_LINKER=gold"
fi

LLVM_SRC_DIR="$ARC_MLIR/llvm-project"
LLVM_BUILD_DIR="$ARC_MLIR_BUILD/llvm-build/"
LLVM_INSTALL_DIR="$ARC_MLIR_BUILD/llvm-install"

ARC_LANG_SRC_DIR="${ARC_MLIR}/../arc-lang/"
ARC_LANG_BUILD_DIR="${ARC_MLIR_BUILD}/arc-lang/"

# default to a debug build
BUILD_FLAVOUR="${BUILD_FLAVOUR:-Debug}"

# Do we want assertions?
ARC_MLIR_ASSERTS="${ARC_MLIR_ASSERTS:+-DLLVM_ENABLE_ASSERTIONS=ON}"

# Do we want ccache?
ARC_MLIR_CCACHE="${ARC_MLIR_CCACHE:+-DLLVM_CCACHE_BUILD=1}"

echo "Will build a $BUILD_FLAVOUR build"

# Report a failure and exit
function fail {
    echo "Failure: $*"
    exit 1
}

function llvm-cmake {

    mkdir -p $LLVM_BUILD_DIR || fail "creating $LLVM_BUILD_DIR"
    cd $LLVM_BUILD_DIR

    if [ -f compile_commands.json ]; then
      echo "LLVM is already configured"
      return
    fi

    CXX=clang++ CC=clang cmake \
       -DCMAKE_GENERATOR="Ninja" \
       -DCMAKE_INSTALL_PREFIX="$LLVM_INSTALL_DIR" \
       -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
       -DCMAKE_BUILD_TYPE=$BUILD_FLAVOUR \
       -DLLVM_TARGETS_TO_BUILD="host" \
       $ARC_MLIR_LINKER_SELECTION \
       $ARC_MLIR_ASSERTS \
       -DBUILD_SHARED_LIBS=0 \
       -DLLVM_USE_SPLIT_DWARF=ON \
       $ARC_MLIR_CCACHE \
       -DLLVM_BUILD_EXAMPLES=OFF \
       -DLLVM_ENABLE_PROJECTS=mlir\
       -DLLVM_EXTERNAL_PROJECTS="arc-mlir" \
       -DLLVM_EXTERNAL_ARC_MLIR_SOURCE_DIR="$ARC_MLIR/src" \
       -DLLVM_HAVE_TF_API="OFF" \
       $LLVM_SRC_DIR/llvm || fail "cmaking LLVM"
}

function llvm-build {
    cmake --build $LLVM_BUILD_DIR || fail "building LLVM"
}

llvm-cmake
llvm-build
