[package]
name = "logging"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
