[package]
name = "ll-parser"
version.workspace = true
edition.workspace = true

[[bin]]
name = "ll-parser"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = "0.2"
chumsky = { git = "https://github.com/zesterer/chumsky.git", version = "1.0.0-alpha.3", features = ["std", "spill-stack", "label", "extension", "sync", "memoization"] }
lexer   = { path = "../lexer"}
logos = "0.12.1"
ast = { path = "../../irs/ast" }
im-rc        = { version = "15.1.0" }
