[package]
name = "arc-script-api-quote"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
arc-script-compiler = { version = "=0.0.0", path = "../../compiler" }

syn                 = { version = "1.0.60", features = ["full"] }
quote               = { version = "1.0.7" }
proc-macro2         = { version = "1.0.21" }
