[package]
name = "state"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [features]
# remote = ["tikv-client"]
# local = ["sled"]
# default = []

[dependencies]
builtins.workspace = true
serde.workspace = true
sled.workspace = true
# tikv-client.workspace = true
tokio.workspace = true
serde_json.workspace = true
