[package]
name = "arc-script-codegen-arcon"
version = "0.0.0"
authors = ["Klas Segeljakt <klasseg@kth.se>"]
edition = "2018"
description = "A bridge between MLIR and Arcon."
license = "MIT"

[dependencies]
arcon         = { version = "0.1.3", git = "https://github.com/segeljakt/arcon" }
arcon_macros  = { version = "0.1.3", git = "https://github.com/segeljakt/arcon" }
prost         = { version = "0.7.0" }
