[package]
name = "timer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "1.3.1"
wheel = { version = "1.2.0", package = "hierarchical_hash_wheel_timer" }
