edition = "2018"
reorder_modules = false
#fn_single_line = true
#format_code_in_doc_comments = true
#format_macro_matchers = true
#format_strings = true
#inline_attribute_width = 20
#normalize_comments = true
#normalize_doc_attributes = true
#overflow_delimited_expr = true
#reorder_impl_items = true
#use_field_init_shorthand = true
