[package]
name = "version"
version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
build = "build.rs"

[dependencies]

[build-dependencies]
built.workspace = true
