name: Arc CI

on: [push]

# Some taken from
# https://github.com/hiyainc-oss/trie-map/blob/5b892223e50854a4e0f9f86cd20c91efb5985126/.github/workflows/scala.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v1    

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Ivy
      uses: actions/cache@v1.0.3
      with:
        path: ~/.ivy2
        key: ${{ runner.os }}-ivy-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/**/*.scala') }}

    - name: Cache SBT
      id: cache-sbt
      uses: actions/cache@v1.0.3
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('**/project/**/*.scala') }}

    - name: Cache arc-frontend
      id: cache-arc-frontend
      uses: actions/cache@v1.0.3
      with:
        path: arc-frontend/target
        key: ${{ runner.os }}-arc-frontend-${{ hashFiles('arc-frontend/*.sbt') }}-${{ hashFiles('arc-frontend/src/**/**') }}

    - name: Cache arc-mlir
      id: cache-arc-mlir
      uses: actions/cache@v1.0.3
      with:
        path: arc-mlir/build
        key: ${{ runner.os }}-arc-mlir-${{ hashFiles('arc-mlir/src/**/**') }}
    
    - name: Build and test arc-frontend
      run: sbt test assembly
      
    - name: Build and test arc-mlir
      run: |
        cd arc-mlir
        ./arc-mlir-build
        cd build/llvm-build/
        ninja check-arc-mlir
